apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: k8s/apache
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: php-fpm
        image: k8s/php-fpm
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
      - name: mysql
        image: k8s/mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: web